from typing import Protocol

from gestor_gastos.dominio.prevision.entidades import (
    AjusteMensual,
    AsociacionConcepto,
    AsociacionDescripcion,
    ConceptoPrevisto,
)


class RepositorioPrevisiones(Protocol):
    """Puerto de persistencia para ConceptoPrevisto."""

    def crear(self, concepto: ConceptoPrevisto) -> ConceptoPrevisto: ...

    def obtener_por_id(self, id_concepto: int) -> ConceptoPrevisto | None: ...

    def listar(self) -> list[ConceptoPrevisto]: ...

    def actualizar(self, concepto: ConceptoPrevisto) -> ConceptoPrevisto: ...

    def eliminar(self, id_concepto: int) -> None: ...

    def contar_por_categoria(self, id_categoria: int) -> int: ...

    def contar_por_subcategoria(self, id_subcategoria: int) -> int: ...

    def eliminar_por_categoria(self, id_categoria: int) -> None: ...

    def eliminar_por_subcategoria(self, id_subcategoria: int) -> None: ...


class RepositorioAjustesMensuales(Protocol):
    """Puerto de persistencia para AjusteMensual."""

    def guardar(self, ajuste: AjusteMensual) -> AjusteMensual:
        """Crea o actualiza (upsert) el ajuste para su clave (concepto_id, anio, mes)."""
        ...

    def eliminar(self, id_concepto: int, anio: int, mes: int) -> None: ...

    def listar_por_anio(self, anio: int) -> list[AjusteMensual]: ...

    def listar_todos(self) -> list[AjusteMensual]: ...


class RepositorioAsociaciones(Protocol):
    """Puerto de persistencia para AsociacionConcepto."""

    def crear(self, asociacion: AsociacionConcepto) -> AsociacionConcepto: ...

    def obtener_por_id(self, id_asociacion: int) -> AsociacionConcepto | None: ...

    def listar(self) -> list[AsociacionConcepto]: ...

    def obtener_por_categoria_resumen(
        self, categoria_resumen_id: int, subcategoria_resumen_id: int | None
    ) -> AsociacionConcepto | None: ...

    def eliminar(self, id_asociacion: int) -> None: ...

    def contar_por_categoria(self, id_categoria: int) -> int:
        """Cuenta las asociaciones que referencian esta categoría, ya sea
        como lado "resumen" o como lado "movimiento"."""
        ...

    def contar_por_subcategoria(self, id_subcategoria: int) -> int:
        """Igual que contar_por_categoria, pero para una subcategoría."""
        ...

    def eliminar_por_categoria(self, id_categoria: int) -> None: ...

    def eliminar_por_subcategoria(self, id_subcategoria: int) -> None: ...


class RepositorioAsociacionesDescripcion(Protocol):
    """Puerto de persistencia para AsociacionDescripcion."""

    def crear(self, asociacion: AsociacionDescripcion) -> AsociacionDescripcion: ...

    def obtener_por_id(self, id_asociacion: int) -> AsociacionDescripcion | None: ...

    def listar(self) -> list[AsociacionDescripcion]: ...

    def obtener_por_descripcion(self, descripcion: str) -> AsociacionDescripcion | None: ...

    def eliminar(self, id_asociacion: int) -> None: ...

    def contar_por_categoria(self, id_categoria: int) -> int: ...

    def contar_por_subcategoria(self, id_subcategoria: int) -> int: ...

    def eliminar_por_categoria(self, id_categoria: int) -> None: ...

    def eliminar_por_subcategoria(self, id_subcategoria: int) -> None: ...
