"""añadir origen a movimientos

Revision ID: 01c260a16a5f
Revises: 01fe6e84ccfb
Create Date: 2026-09-05 08:57:58.842900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c260a16a5f'
down_revision: Union[str, Sequence[str], None] = '01fe6e84ccfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos', sa.Column('origen', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimientos', 'origen')
    # ### end Alembic commands ###
