"""crear asociaciones_descripciones

Revision ID: 01fe6e84ccfb
Revises: f39d45167b74
Create Date: 2026-08-30 12:51:09.141956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fe6e84ccfb'
down_revision: Union[str, Sequence[str], None] = 'f39d45167b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociaciones_descripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_resumen_id', sa.Integer(), nullable=False),
    sa.Column('subcategoria_resumen_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['categoria_resumen_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_resumen_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asociaciones_descripciones')
    # ### end Alembic commands ###
