"""crear cuentas bancarias, categorias, subcategorias y movimientos

Revision ID: 2ff9412e73b8
Revises: 
Create Date: 2026-08-16 17:40:32.510307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff9412e73b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=True),
    sa.Column('entidad_bancaria', sa.String(length=120), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('titular', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_bancarias_numero_cuenta'), 'cuentas_bancarias', ['numero_cuenta'], unique=True)
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', 'nombre')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('fecha_valor', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_bancarias.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'fecha_valor', 'importe', 'saldo', 'descripcion', name='uq_movimiento_deduplicacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos')
    op.drop_table('subcategorias')
    op.drop_index(op.f('ix_cuentas_bancarias_numero_cuenta'), table_name='cuentas_bancarias')
    op.drop_table('cuentas_bancarias')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
