"""crear ajustes prevision mensual

Revision ID: 52eeab508696
Revises: b4ebee66f937
Create Date: 2026-08-19 19:20:42.083043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52eeab508696"
down_revision: Union[str, Sequence[str], None] = "b4ebee66f937"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ajustes_prevision_mensual",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concepto_id", sa.Integer(), nullable=False),
        sa.Column("anio", sa.Integer(), nullable=False),
        sa.Column("mes", sa.Integer(), nullable=False),
        sa.Column("importe", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["concepto_id"], ["conceptos_previstos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("concepto_id", "anio", "mes"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ajustes_prevision_mensual")
    # ### end Alembic commands ###
