"""crear conceptos previstos

Revision ID: b4ebee66f937
Revises: 2ff9412e73b8
Create Date: 2026-08-19 17:48:13.484973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ebee66f937'
down_revision: Union[str, Sequence[str], None] = '2ff9412e73b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos_previstos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('periodicidad', sa.String(length=20), nullable=False),
    sa.Column('mes_inicio', sa.Integer(), nullable=True),
    sa.Column('importe_previsto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conceptos_previstos')
    # ### end Alembic commands ###
