"""crear asociaciones conceptos

Revision ID: f39d45167b74
Revises: 52eeab508696
Create Date: 2026-08-29 19:43:42.541045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39d45167b74'
down_revision: Union[str, Sequence[str], None] = '52eeab508696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociaciones_conceptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_resumen_id', sa.Integer(), nullable=False),
    sa.Column('subcategoria_resumen_id', sa.Integer(), nullable=True),
    sa.Column('categoria_movimiento_id', sa.Integer(), nullable=False),
    sa.Column('subcategoria_movimiento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_movimiento_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['categoria_resumen_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_movimiento_id'], ['subcategorias.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_resumen_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_resumen_id', 'subcategoria_resumen_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asociaciones_conceptos')
    # ### end Alembic commands ###
