from typing import Protocol

from gestor_gastos.dominio.categoria.entidades import Categoria, Subcategoria


class RepositorioCategorias(Protocol):
    """Puerto de persistencia para Categoria y Subcategoria."""

    def crear_categoria(self, categoria: Categoria) -> Categoria: ...

    def obtener_categoria_por_id(self, id_categoria: int) -> Categoria | None: ...

    def obtener_categoria_por_nombre(self, nombre: str) -> Categoria | None: ...

    def listar_categorias(self) -> list[Categoria]: ...

    def actualizar_categoria(self, categoria: Categoria) -> Categoria: ...

    def eliminar_categoria(self, id_categoria: int) -> None: ...

    def contar_subcategorias(self, id_categoria: int) -> int: ...

    def eliminar_subcategorias_de(self, id_categoria: int) -> None: ...

    def crear_subcategoria(self, subcategoria: Subcategoria) -> Subcategoria: ...

    def obtener_subcategoria_por_id(self, id_subcategoria: int) -> Subcategoria | None: ...

    def obtener_subcategoria_por_nombre(
        self, id_categoria: int, nombre: str
    ) -> Subcategoria | None: ...

    def listar_subcategorias_de(self, id_categoria: int) -> list[Subcategoria]: ...

    def actualizar_subcategoria(self, subcategoria: Subcategoria) -> Subcategoria: ...

    def eliminar_subcategoria(self, id_subcategoria: int) -> None: ...
