import datetime
from decimal import Decimal
from typing import Protocol

from gestor_gastos.dominio.movimiento.entidades import Movimiento


class RepositorioMovimientos(Protocol):
    """Puerto de persistencia para Movimiento."""

    def crear(self, movimiento: Movimiento) -> Movimiento: ...

    def obtener_por_id(self, id_movimiento: int) -> Movimiento | None: ...

    def listar_todos(self) -> list[Movimiento]: ...

    def listar_por_cuenta(self, id_cuenta: int) -> list[Movimiento]: ...

    def listar_por_categoria(
        self, id_categoria: int, solo_gastos: bool = False
    ) -> list[Movimiento]: ...

    def listar_por_subcategoria(
        self, id_subcategoria: int, solo_gastos: bool = False
    ) -> list[Movimiento]: ...

    def actualizar(self, movimiento: Movimiento) -> Movimiento: ...

    def eliminar(self, id_movimiento: int) -> None: ...

    def buscar_duplicado(
        self,
        id_cuenta: int,
        fecha_valor: datetime.date,
        importe: Decimal,
        saldo: Decimal,
        descripcion: str,
    ) -> Movimiento | None: ...

    def contar_movimientos_por_cuenta(self, id_cuenta: int) -> int: ...

    def contar_movimientos_por_categoria(self, id_categoria: int) -> int: ...

    def contar_movimientos_por_subcategoria(self, id_subcategoria: int) -> int: ...

    def eliminar_movimientos_por_cuenta(self, id_cuenta: int) -> None: ...

    def eliminar_movimientos_por_categoria(self, id_categoria: int) -> None: ...

    def eliminar_movimientos_por_subcategoria(self, id_subcategoria: int) -> None: ...

    def actualizar_categoria_de_movimientos_por_subcategoria(
        self, id_subcategoria: int, id_categoria: int
    ) -> None: ...

    def obtener_ultimo_saldo(self, id_cuenta: int) -> Decimal | None: ...

    def sumar_gastos_por_categoria(self) -> dict[int, Decimal]: ...

    def sumar_ingresos_por_categoria(self) -> dict[int, Decimal]: ...

    def sumar_movimientos_por_mes(
        self, anio: int
    ) -> dict[tuple[int, int | None, int], Decimal]: ...
